version: '3.8'
services:
  web:
    build: ./test_case
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE
    env_file:
      - .env
